### ISSUE TITLE
Nest Developer Page Change

### ISSUE THREAD

**Issue by DeaFroggatt** [zpeters/nerdnest#16]
Followed procedures to create Nest Developers Account on the nerdnest wiki..  Although the Product Details and steps that now appear at https://developers.nest.com do not appear as indicated on the page created by Zach Peters, Feb 2, 2017.
Subsequently I had difficulty completing the step "Registering nerdnest with your account".  The Authorization URL took me to a page unrecognized page.
Is there a revised version to these instructions that match the current Nest Developer page??

**Comment by zpeters** [comment]
Dupe of #15
